JOLO_WEBSITE/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import homepage

#all urls for the entire project
#urls per app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
    path('projects/', include('projects.urls')),
    path('template/', include('template.urls')),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
#stores all urls that are associated with the app
urlpatterns = [
    path('', views.index, name='index'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
#stores all urls that are associated with the app
urlpatterns = [
    path('', views.index, name='index'),
]

template/urls.py
from django.urls import path
from . import views

app_name = 'template'
#stores all urls that are associated with the app
urlpatterns = [
    path('', views.index, name='index'),
]

homepage/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
class Skill(models.Model):
    name = models.CharField(max_length=64)
    level = models.IntegerField()
    description = models.CharField(max_length=200)
    icon_html = models.CharField(max_length=200, default='fa-solid fa-question')
    def __str__(self):
        return f"{self.name}: {self.level}"


class Education(models.Model):
    schoolName = models.CharField(max_length=150)
    degree = models.CharField(max_length=150)
    startYear = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2999)])
    endYear = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2999)],null=True)
    logo = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"{self.schoolName}"

projects/models.py
from django.db import models

# Create your models here.

template/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import Skill, Education
# Create your views here.

def index(request):
    return render(request, 'home/index.html',{
        'skills': Skill.objects.all(),
        'educations': Education.objects.all()
    })

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, 'projects/index.html')

template/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
    return render(request, 'template/index.html')

homepage/templates/home/index.html
{%extends "home/navbar.html"%} {%block body%} {%load static%}
<!-- ======= Home Section ======= -->
<section id="home" class="d-flex align-items-center">
  <div
    id="scrollhome"
    class="container position-relative"
    data-aos="fade-up"
    data-aos-delay="500"
  >
    <h1>John Paolo "Jolo" Hernandez</h1>
    <h2>Future Software Engineer</h2>
    <a href="{%static 'homepage/JohnPaolo_Hernandez_Resume.pdf'%}" class="btn-get-started" download="">Download Resume</a>
  </div>
</section>

<main id="main">
  <section id="about" class="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left">
          <img src="{%static 'homepage/img/profile_pic.jpeg'%}" class="img-fluid" alt="" />
        </div>
        <div
          class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content"
          data-aos="fade-right"
        >
          <h1>About me</h1>
          <p>
            A current CalStateLA student, pursuing a BS degree in Computer
            Science, and is interested in working for an organization as a Software
            Engineer/Developer.
          </p>
          <ul>
            <li>
              <i class="fa-solid fa-circle-check"></i> Proficient in programming
              fundamentals
            </li>
            <li>
              <i class="fa-solid fa-circle-check"></i> Generally knowledgeable about
              computer technology in terms of troubleshooting, networking, and security
            </li>
            <li>
              <i class="fa-solid fa-circle-check"></i> Passionate in learning new things about
              computer science.
            </li>
            <li>
              <i class="fa-solid fa-circle-check"></i> Experience in interpersonal communication.
            </li>
          </ul>
          <p>
            Outside of school, I spend most of my spare time building simple projects in order
            to improve my skills as a Software Developer.
          </p>
          <br/>
          <p><i class="fa-solid fa-circle-info"></i> The following link directs to my
            Github repository that contains my projects.</p>
          <a href="https://github.com/LudiJolo/jhernandez-portfolio.git" class="btn-get-started" target="_blank">
            <button type="button" class="btn btn-outline-danger">
              Github
            </button></a>
        </div>
      </div>
    </div>
  </section>
  <!-- End About Section -->

  <!-- ======= Skills Section ======= -->
<section id="skills" class="skills">
  <div class="container">

    <div class="section-title">
      <span>Skills</span>
      <h2>Skills</h2>
      <p>These are the {{skills.count}} skills that I have obtained and improving since the start of my college career</p>
    </div>

    <div id="skill_row" class="row">
      {%for skill in skills%}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4" data-aos="fade-down">
          <div class="icon-box" style="width: 100%;">
            <div class="icon"><i class="{{skill.icon_html}}"></i></div>
            <h4>{{forloop.counter}}: {{skill.name}}</h4>
            <p>{{skill.description}}</p>
          </div>
        </div>
      {%endfor%}
  </div>
</section><!-- End Skills Section -->

<!-- ======= Education Section ======= -->
<section id="education" class="education">
  <div class="container">

    <div class="section-title">
      <span>Education</span>
      <h2>Education</h2>
      <p>These are the schools that I have attended</p>
    </div>

    <div class="row">
    {%for ed in educations%}
      <div class="col-lg-6 col-md-12 d-flex align-items-stretch mt-4" data-aos-delay="300" data-aos="fade-up">
        <div class="ed-box" style="width: 100%;">
          <div class="icon"><img src="{{STATIC_URL}}/static/homepage/img/{{ed.logo}}"></div>
          <h2>{{ed.schoolName}}</h2>
          <p class="ed-year">{{ed.startYear}} - {{ed.endYear}}</p>
          <p>{{ed.degree}}</p>
        </div>
      </div>
    {%endfor%}
  </div>
</section>
<!-- End Education Section -->
  <!-- ======= Contact Section ======= -->
  <section id="contact" class="contact">
    <div class="container">
      <div class="section-title">
        <span>Contacts</span>
        <h2>Contacts</h2>
      </div>

      <div class="row" data-aos="fade-up">
        <div class="col-lg-4 text-center">
          <div class="info-box mb-4">
            <i class="fa-solid fa-location-dot"></i>
            <h3>Location</h3>
            <p>Los Angeles, California</p>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 text-center">
          <div class="info-box mb-4">
            <i class="fa-solid fa-envelope"></i>
            <h3>My Email</h3>
            <a href="mailto:joloh18@yahoo.com">joloh18@yahoo.com</a>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 text-center">
          <div class="info-box mb-4">
            <i class="fa-solid fa-phone"></i>
            <h3>Phone Number</h3>
            <p>626 549 9045</p>
          </div>
        </div>
      </div>

      <div class="row" data-aos="fade-up">
        <!--
            <div class="col-lg-6 ">
              <iframe class="mb-4 mb-lg-0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe>
            </div>
  
          -->
        <div
          class="col-lg-12 container-fluid mx-auto p-5 rounded-4"
          style="width: 65%"
          id="msg_box"
        >
        </div>
      </div>
    </div>
  </section>
  <!-- End Contact Section -->
</main>
{%endblock%}

homepage/templates/home/messagesent.html
<h>Thank you {{message_name}}</h>
<p>Message has been sent</p>

homepage/templates/home/navbar.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Jolo's Website</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://kit.fontawesome.com/6415f21007.js" crossorigin="anonymous"></script>

  <!--Main CSS file-->
  <link rel="stylesheet" href="{%static 'homepage/styles.css'%}">
    
  

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
</head>
<!-- ======= Top Bar ======= -->
<section id="topbar" class="d-flex align-items-center">
  <div class="container d-flex justify-content-center justify-content-md-between">
    <div class="contact-info d-flex align-items-center">
      <i class="bi bi-envelope-fill"></i><a href="mailto:joloh18@yahoo.com">joloh18@yahoo.com</a>
      <i class="bi bi-phone-fill phone-icon"></i> 626 549 9045
    </div>
    <div class="social-links d-none d-md-block">
      <a href="https://github.com/LudiJolo/jhernandez-portfolio.git" class="github" target="_blank"><i class="bi bi-github" ></i></a>
      <a href="https://www.linkedin.com/in/jolohernandez18/" class="linkedin" target="_blank"><i class="bi bi-linkedin" ></i></i></a>
    </div>
  </div>
</section>


<!-- ======= NavBar ======= -->
<header id="header" class="d-flex align-items-center">
  <div class="container d-flex align-items-center justify-content-between">
    <h1 class="logo"><a href="{%url 'homepage:index'%}"> Jolo H.</a></h1>
    <nav id="navbar" class="navbar">
      <ul>
        <li><a class="nav-link scrollto active" href="#home">Home</a></li>
        <li><a class="nav-link scrollto" href="#about">About</a></li>
        <li><a class="nav-link scrollto" href="#skills">Skills</a></li>
        <li><a class="nav-link scrollto" href="#education">Education</a></li>
        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
      </ul>
      <i class="bi bi-list mobile-nav-toggle"></i>
    </nav>

  </div>
</header>

{%block body%}
{%endblock%}

<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
  AOS.init();
</script>
<script src="{%static 'homepage/home.js'%}"></script>
</body>
</html>

projects/templates/projects/index.html
{%extends "home/navbar.html"%} {%block body%}
<section id="projects" class="projects">
  <h1>Projects</h1>
</section>
{%endblock%}

template/templates/template/index.html
{%extends "home/navbar.html"%} {%block body%}
<section class="hero">
  <div class="hero__slider owl-carousel owl-loaded">
    <div class="owl-stage-outer">
      <div
        class="owl-stage"
        style="
          transform: translate3d(-1896px, 0px, 0px);
          transition: all 0s ease 0s;
          width: 4424px;
        "
      >
        <div
          class="owl-item animated owl-animated-in fadeIn cloned"
          style="width: 632px"
        >
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="owl-item cloned" style="width: 632px">
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="owl-item" style="width: 632px">
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          class="owl-item animated owl-animated-in fadeIn active"
          style="width: 632px"
        >
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          class="owl-item animated owl-animated-in fadeIn"
          style="width: 632px"
        >
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="owl-item cloned" style="width: 632px">
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          class="owl-item animated owl-animated-in fadeIn cloned"
          style="width: 632px"
        >
          <div
            class="hero__item set-bg"
            data-setbg="img/hero/hero-1.jpg"
            style="background-image: url('img/hero/hero-1.jpg')"
          >
            <div class="container">
              <div class="row">
                <div class="col-lg-6">
                  <div class="hero__text">
                    <span>For website and video editing</span>
                    <h2>Videographer’s Portfolio</h2>
                    <a href="#" class="primary-btn">See more about us</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="owl-nav disabled">
      <button type="button" role="presentation" class="owl-prev">
        <span aria-label="Previous">‹</span></button
      ><button type="button" role="presentation" class="owl-next">
        <span aria-label="Next">›</span>
      </button>
    </div>
    <div class="owl-dots">
      <button role="button" class="owl-dot">01</button
      ><button role="button" class="owl-dot active">02</button
      ><button role="button" class="owl-dot">03</button>
    </div>
  </div>
</section>
{%endblock%}

theme/templates/theme/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>